version: {build}

branches:
  only:
    - master
    - develop

environment:
  matrix:
    - PYTHON: "C:\\Python34-x64"
      TOXENV: "py34"
    - PYTHON: "C:\\Python35-x64"
      TOXENV: "py35"
    - PYTHON: "C:\\Python36-x64"
      TOXENV: "py36"

install:
  - "%PYTHON%\\python.exe -m pip install tox"

build: off

test_script:
  - "%PYTHON%\\python.exe -m tox"

notifications:
  - provider: Email
    to:
      - jared@kotfu.net
    subject: 'tomcatmanager appveyor build {{status}}'
    on_build_status_changed: true
