# theme template for tomcat-manager
#
# This file is in TOML format, see https://toml.io/en/ for more information.
#
# A theme consists of scopes and a style for each scope.
#
# In this example:
#
#   [tm.help]
#   section = "gold1"
#
# "tm.help.section" is a theme scope, and "gold1" is the style. The TOML file
# format allows you to specify a theme scope using several different
# syntaxes. This syntax yields the same result:
#
#   tm.help.section = "gold1"
#
# All theme scopes are present in this file, but set to "default".
# The theme scopes are all present to make it easy for you to
# customize them. "default" means to apply no color or styling, making this
# theme template the visual equivilent of no theme.
#
# You can set a style for each theme scope. A style can specify colors
# and attributes (like bold or italic). Ancient terminals are monochrome,
# really old terminals could display 16 colors, old terminals can display
# 256 colors, most modern terminals can display 16.7 million colors.
#
# Specify a color using any of the following:
#
#   #8700af           CSS-style hex notation
#   rgb(135,0,175)    RGB form using three integers
#   dark_magenta      color names
#   color(91)         color numbers
#
# Color names and numbers are shown at
# https://rich.readthedocs.io/en/stable/appendix/colors.html
#
# All of the above forms produce the exact same color.
#
# By itself, a color will set the foreground color. To set the background
# color, preceed the color with the word "on".
#
#   white on rgb(135,0,75)
#   #ffffff on dark_magenta
#
# Specify additional text attributes by adding additional words to the style:
#
#   #ffffff on #8700af bold strike
#   color(91) underline
#
# The most useful text attributes are:
#
#   bold        bold text
#   italic      italic text (not supported on Windows)
#   strike      text with a strikethrough line
#   underline   underlined text
#
# For more examples and additional documentation on styles, see
# https://rich.readthedocs.io/en/stable/style.html
#
# More documentation on themes and how they work is available at
# https://tomcatmanager.readthedocs.io/en/stable/interactive/themes.html
#

# theme metadata
description = "new theme"

# These scopes are applied to output generated by many commands.
[tm]
# error messages
error =  "default"
# status messages
status =  "default"
# progress animations for long-running commands (like connect or list)
animation = "default"


# When run with no arguments, the 'help' command shows a categorized list
# of all the available commands. These scopes control the display of that
# categorized list.
[tm.help]
# the name of a category or grouping of commands
category =  "default"
# the border line below the category  name
border = "default"
# the name of the command shown in the first column
command =  "default"
# arguments to the 'help' command
args = "default"


# These scopes are used when displaying help or usage for a specific command
# i.e. when typing 'connect -h' or 'help connect'.
[tm.usage]
# name of the command
prog =  "default"
# groups of arguments, ie 'positional arguments:', and 'options:'
groups =  "default"
# the positional arguments and options
args =  "default"
# values for options, ie KEY is the metavar in '--key KEY'
metavar =  "default"
# the description of positional arguments and options
help =  "default"
# command descriptions, epilogs, and other text
text =  "default"
# syntax or references inline in other text
syntax =  "default"


# Used by the 'list' command which shows information about each
# application deployed in the Tomcat server.
[tm.list]
# column headers in the table of displaye dinformation
header =  "default"
# the border line underneath the column headers
border =  "default"


# When showing details of an app deployed in a tomcat server,
# like by the list command, use these scopes for attributes
# of each application.
[tm.app]
# if the application is running, show the word 'running' in this style
running =  "default"
# if the application is stopped, show the word 'stopped' in this style
stopped =  "default"
# show the number of active sessions in this style
sessions =  "default"

# These scopes are used by the 'settings' command to show the various
# program settings.
[tm.setting]
# name of the setting
name =  "default"
# the equals sign separating the setting from it's value
equals =  "default"
# the comment containing the description of the setting
comment =  "default"
# values which are strings, like 'prompt'
string =  "default"
# values which are boolean, like 'debug' and 'echo
bool =  "default"
# values which are integers, we have no settings with integer values
# but have added it to all themes just in case
int =  "default"
# values which are floats, like 'timeout'
float =  "default"


# These scopes used by the 'theme list' command to show all available themes
[tm.theme]
# the category or group name of a set of themes
category = "default"
# the border line below the category name
border = "default"
